version: "3.8"

services:
  web:
    image: nossobr
    container_name: nossobr_api
    ports:
      - 9090:9090
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: nossobr
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
