version: "3.8"

services:
  api:
    image: nossobr
    container_name: nossobr_api
    ports:
      - 9090:9090
    depends_on:
      postgesql:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  postgesql:
    image: 'postgres:14.1-alpine'
    container_name: nossobr_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nossobr
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
